### ISSUE TITLE
snake case is demonstrated using italics instead of underscores.

### ISSUE THREAD

**Issue by mathlete01** [learn-co-curriculum/sql-database-basics#2]

**Comment by bal360** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
